platform :ios, '13.0'
use_frameworks!

target 'LifeLibrary' do
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'SwiftLint'
  pod 'SnapKit'
  pod 'Then'
  pod 'RxGesture'
  pod 'FSCalendar'
end

inhibit_all_warnings! # cocoapods의 swiftlint 경고 메시지 해제
post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts target.name
  end
end
